Support PHP 5.2
Automattic/component-themes pull request #13
Opened 2016-12-15 16:29 UTC by taggon

See #5.

As WordPress supports PHP 5.2, we're supposed to do so. This PR will downgrade and modify the PHP scripts to support the old version.

Todo:
- Server scripts
  - [ ] Component_Themes
  - [x] Component_Themes_Api
  - [x] Component_Themes_Api_wrapper
  - [ ] Component_Themes_Builder
  - [x] Component_Themes_Component
  - [ ] Component_Themes_Styles
  - [ ] React
  - [ ] helper functions
- Components
  - [ ] ColumnComponent
  - [ ] FooterText
  - [ ] HeaderText
  - [ ] MenuWidget
  - [ ] PageLayout
  - [ ] PostBody
  - [ ] PostContent
  - [ ] PostDate
  - [x] PostList
  - [ ] PostTitle
  - [ ] RowComponent
  - [ ] SearchWidget
  - [ ] SinglePost
  - [ ] TextWidget

2016-12-20 21:06 UTC, sirbrillig requested changes
This looks amazing. Nice work all around! A few things:

- There were a couple of typos I saw where I left a comment.
- You might want to install `phpcs` and the WordPress style pack to check your styles. I just installed it recently and learned a few things that I had been doing incorrectly. I marked a few places where I saw an error appear in my editor.
- When I try to run this branch on my test site, I get a bunch of PHP warnings. You can test the output by commenting-out line 85 of public/class-component-themes-public.php which will cause only the PHP version to be rendered.

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-api-wrapper.php
> +		foreach ( $api_props as $name=>$prop ) {
(Style) Can you add spaces around the `=>`?

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-builder.php
> +		foreach( $this->props as $name=>$value ) {
(Style) Can you add spaces around `=>`?

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-builder.php
> +			$noop = create_function( '', '' );
TIL! 👍

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-builder.php
> +			foreach( $component_config['children'] as $key=>$child ) {
(Style) Spaces around `=>`

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-builder.php
> +			$chilren = array();
s/$chilren/$children/

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-styles.php
> +		$parser = new CssParser();
Whoops! Nice find.

2016-12-20 21:06 UTC, sirbrillig commented on server/class-component-themes-component-wrapper.php
> +		if ( is_string( $component) && is_subclass_of( $component, 'Component_Themes_Component' ) ) {
(Style) There's a missing space after `is_string( $component`

2016-12-20 21:06 UTC, sirbrillig commented on server/class-react.php
> +		$rendered_children = array_filter( $rendered_children, 'ct_not_empty' );
Nice!

2016-12-20 21:06 UTC, sirbrillig commented on src/themes/components/MenuWidget/index.php
> +		$title = $this->get_prop( 'title', '' );
Setting a default here will cause the title markup to be shown even if the title is empty because the next line uses `isset()`. The intent was to not show the title area at all if no title is present.

2016-12-20 21:06 UTC, sirbrillig commented on src/themes/components/SinglePost/index.php
> +	$new_children = React::cloneChileren( $children, $post_data );
s/cloneChileren/cloneChildren/

2016-12-22 13:21 UTC, taggon commented
@sirbrillig Hey! I fixed all typos and styles. :)

2016-12-22 17:41 UTC, sirbrillig commented
I'm still seeing errors:

```
Notice: Undefined variable: component in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-component-wrapper.php on line 11

Notice: Undefined variable: component in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-component-wrapper.php on line 15

Notice: Undefined variable: component in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-component-wrapper.php on line 11

Notice: Undefined variable: component in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-component-wrapper.php on line 15

Notice: Undefined variable: component in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-component-wrapper.php on line 11

Notice: Undefined variable: component in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-component-wrapper.php on line 15

Warning: array_merge(): Argument #1 is not an array in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-builder.php on line 85

Warning: Invalid argument supplied for foreach() in /srv/www/wordpress-default/wp-content/plugins/component-themes/server/class-component-themes-builder.php on line 38
```

I just pushed a commit to allow rendering a page using just the PHP. If you add `?ssr=true` to the URL, it will not activate the javascript rendering. This should make it easier to test.

2016-12-23 08:17 UTC, taggon commented
@sirbrillig I wasn't be able to see the errors because `WP_DEBUG` was turned off in my local machine. My bad. 😛  Now all the errors seem to be fixed.

2016-12-23 22:08 UTC, sirbrillig commented
Nice! Errors are gone. 

Testing the `home` template works great. The `post` template, however, seems to not be getting the data from the API and I'm not sure why (I'm just seeing the default "No title", "No date", etc.).

To test this template, click on the post title of any post listed on the home page.

2017-01-03 16:09 UTC, sirbrillig approved these changes

2017-01-03 16:10 UTC, sirbrillig commented
Nice work!

2017-01-04 08:59 UTC, merged